name: Terraform Static Analysis
on: 
  push:
    branches-ignore: 
      - main

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  terrascan:
    runs-on: ubuntu-latest
    name: terrascan-action
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@v1.5.0
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        
    - name: Check for file
      shell: bash
      run: cat terrascan.sarif

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: terrascan.sarif
